#server:
#    port: 1111
spring:
    datasource:
        url: jdbc:mysql://zodaland.com:3306/gradle
        username: eksl12
        password: zodaland
        #driver-class-name: org.mysql.jdbc.Driver
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp
    resource:
        static-locations: classpath:/resources/,classpath:/static/
    devtools:
        livereload:
            enabled: true
mybatis:
    type-aliases-package: test.spring.mapper
    mapper-locations: mybatis/mapper/**/*.xml
